name: Build Our AMI 
run-name: ${{ github.actor }} is building AMI
#on: [push]
on:
  pull_request:
    types:
      - closed
      
jobs:
  BuildMyAppContainerImage:
    if: github.event.pull_request.merged == true    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Does this thing work?"
      - name: Setup Code
        uses: actions/checkout@v4
      - name: Check that checkout worked
        run: ls -lh
      - name: Get Packer
        run: sudo apt install -y packer
      - name: Build Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          packer init .
          packer build packer_with_provisioner.pkr.hcl      
