name: Build Our Container 
run-name: ${{ github.actor }} is building container
on:
  workflow_dispatch:
  
jobs:
  BuildMyAppContainerImage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Does this work?"
      - name: Setup Code
        uses: actions/checkout@v4
      - name: Check that checkout worked
        run: ls -lh
      - name: Get Docker
        run: sudo apt install -y docker
      - name: Build Image
        run: docker image build .
      
