name: Build Our Container 
run-name: ${{ github.actor }} is building container
on:
  pull_request:
    types: [opened, reopened]
  
jobs:
  BuildMyAppContainerImage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Does this work well?"
      - name: Setup Code
        uses: actions/checkout@v4
      - name: Check that checkout worked
        run: ls -lh
      - name: Get Docker
        run: sudo apt install -y docker
      - name: Build Image
        run: docker build --tag dummy_webapp .
      - name: Docker run
        run: docker run -d -p 12344:12344 dummy_webapp
      - name: check if web app is up
        run: curl -Is http://localhost:12344        
        
